# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

title: growmobily
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "" # not sure what this was

permalink: /blog/:title
      
description: "We're cool app devs"
author:
  name: Josh Freckleton
  business: Intelligence Ventures, Corp.
  email: freckletonj@gmail.com
  github: freckletonj
  #twitter: x
  #pinterest: asd123
  linkedin: joshfreckleton
  bio: "we craft nice apps"

rss_path: feed.xml
tags_path: tags.html

collections:
  projects:
    output: true
    permalink: /projects/:title
    

# set it as url of an image
#sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

# gems:
#   - jekyll-paginate
